/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:11fa768b-69e8-4d28-9c26-b6bed0dfa8ae",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_opEZKIRVm",
    "aws_user_pools_web_client_id": "s0brsh8q8f40qg1l55fvjeaqf",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://nrxeao43oba3df6s7yoaid5oqy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bvi4e7xvgfgkfeuvyjknwrias4",
    "aws_user_files_s3_bucket": "work1m59cd9ad6f40d34f4ca2835a9ee7abbd80184612-amplify",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
